sudo: required
services:
 - docker

script:
 - docker run youstest/docker-react npm run test -- --coverage

before_install:
 - docker build -t youstest/docker-react -f Dockerfile.dev .

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "react-frontend"
 env: "ReactFrontend-env"
 bucket_name: "elasticbeanstalk-us-east-2-631216135234"
 bucket_path: "react-frontend"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
